from pydantic import BaseModel

INVALID_IMAGE = "INVALID_IMAGE"
INVALID_DEVICE_ID = "INVALID_DEVICE_ID"
INVALID_REQUEST = "INVALID_REQUEST"
OCR_NO_FORMULA = "OCR_NO_FORMULA"
HISTORY_NOT_FOUND = "HISTORY_NOT_FOUND"
RATE_LIMITED = "RATE_LIMITED"
LLM_TIMEOUT = "LLM_TIMEOUT"
LLM_INVALID_RESPONSE = "LLM_INVALID_RESPONSE"
LLM_CONTENT_POLICY = "LLM_CONTENT_POLICY"
INTERNAL_ERROR = "INTERNAL_ERROR"


class ErrorResponse(BaseModel):
    code: str
    message: str
    retryable: bool
